[build.environment]
  DART_SASS_VERSION = "1.88.0"
  HUGO_VERSION = "0.147.2"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://hugo-theme-nightfall.netlify.com"

[build]
  publish = "public"
  command = "hugo"
